parameters:
#    statistics.example.class: tuttifruttiweb\StatisticsBundle\Example

services:
#    statistics.example:
#        class: %statistics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
