<?php

namespace Proxies\__CG__\tuttifruttiweb\CategoryBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \tuttifruttiweb\CategoryBundle\Entity\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'id', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'name', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'isFixed', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'isReported', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'hits', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'reportedWords', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'acceptedWords');
        }

        return array('__isInitialized__', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'id', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'name', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'isFixed', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'isReported', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'hits', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'reportedWords', '' . "\0" . 'tuttifruttiweb\\CategoryBundle\\Entity\\Category' . "\0" . 'acceptedWords');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function set($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set', array($data));

        return parent::set($data);
    }

    /**
     * {@inheritDoc}
     */
    public function addAcceptedWordsBatch($acceptedWordsBatch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAcceptedWordsBatch', array($acceptedWordsBatch));

        return parent::addAcceptedWordsBatch($acceptedWordsBatch);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFixed($isFixed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFixed', array($isFixed));

        return parent::setIsFixed($isFixed);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFixed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFixed', array());

        return parent::getIsFixed();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsReported($isReported)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsReported', array($isReported));

        return parent::setIsReported($isReported);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsReported()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsReported', array());

        return parent::getIsReported();
    }

    /**
     * {@inheritDoc}
     */
    public function getReportedWordsAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportedWordsAmount', array());

        return parent::getReportedWordsAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setHits($hits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHits', array($hits));

        return parent::setHits($hits);
    }

    /**
     * {@inheritDoc}
     */
    public function getHits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHits', array());

        return parent::getHits();
    }

    /**
     * {@inheritDoc}
     */
    public function addReportedWord(\tuttifruttiweb\CategoryBundle\Entity\ReportedWord $reportedWords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReportedWord', array($reportedWords));

        return parent::addReportedWord($reportedWords);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReportedWord(\tuttifruttiweb\CategoryBundle\Entity\ReportedWord $reportedWords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReportedWord', array($reportedWords));

        return parent::removeReportedWord($reportedWords);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportedWords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportedWords', array());

        return parent::getReportedWords();
    }

    /**
     * {@inheritDoc}
     */
    public function addAcceptedWord(\tuttifruttiweb\CategoryBundle\Entity\AcceptedWord $acceptedWords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAcceptedWord', array($acceptedWords));

        return parent::addAcceptedWord($acceptedWords);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAcceptedWord(\tuttifruttiweb\CategoryBundle\Entity\AcceptedWord $acceptedWords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAcceptedWord', array($acceptedWords));

        return parent::removeAcceptedWord($acceptedWords);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptedWords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptedWords', array());

        return parent::getAcceptedWords();
    }

}
