parameters:
#    utils.example.class: tuttifruttiweb\UtilsBundle\Example

services:
#    utils.example:
#        class: %utils.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
