statistics:
    resource: "@StatisticsBundle/Resources/config/routing.yml"
    prefix:   /

utils:
    resource: "@UtilsBundle/Resources/config/routing.yml"
    prefix:   /

category:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /
