security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            http_basic:
                realm: "No se permite el acceso"

    access_control:
        - { path: ^/category/, roles: ROLE_ADMIN }
        - { path: ^/statistics, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    samaro:  { password: tutti123, roles: 'ROLE_ADMIN' }
                    nguivi: { password: tutti123, roles: 'ROLE_ADMIN' }
                    mcortes: { password: tutti123, roles: 'ROLE_ADMIN' }
                    kbardi: { password: tutti123, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
